name: Run Go Unit Tests on Master

on:
  push:
    branches: ["master"]
    paths:
      - '**/*.go'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod

      - name: Go Version
        run: go version
        continue-on-error: true

      - name: Run Go Unit Tests
        run: go test -v ./...